### ISSUE TITLE
Frontend Navbar

### ISSUE THREAD

**Issue by mpilomthiyane97** [NokulungaM/DataForgeAI-Capstone-FullStack#7]
## Task Description 
Design and implement a responsive navbar for the Recipe Finder frontend. The navbar should include links to Home, Recipes, Sign In/Sign Up, and Saved Recipes (if the user is logged in). It should also include a search bar for quickly finding recipes.

## Task Breakdown

- [ ] Design the navbar layout and make it responsive for different screen sizes.
- [ ]  Implement links for Home, Recipes, Sign In/Sign Up, and Saved Recipes.
- [ ] Add a search bar for users to input ingredients.
- [ ]  Style the navbar using CSS.

## Attachments Provide any design files or screenshots of the navbar mockup.

**Comment by mpilomthiyane97** [comment]
<img width="541" alt="nav-bar" src="https://github.com/user-attachments/assets/8124d925-a178-4d39-95e0-3701a54cf226">

**Comment by NokulungaM** [comment]
Completed
