### ISSUE TITLE
Frontend Footer

### ISSUE THREAD

**Issue by mpilomthiyane97** [NokulungaM/DataForgeAI-Capstone-FullStack#8]
## Task Description 
Design and implement a footer for the Recipe Finder frontend. The footer should include links to the About page, Privacy Policy, Terms of Service, and contact information.

## Task Breakdown

- [ ] Design the footer layout and make it responsive.
- [ ] Include links to About, Privacy Policy, and Terms of Service.
- [ ] Add contact information (email or social media links).
- [ ] Style the footer using CSS.

## Attachments Provide any design files or screenshots of the footer mockup.

**Comment by mpilomthiyane97** [comment]
<img width="824" alt="Footer" src="https://github.com/user-attachments/assets/5563a403-c425-4ef8-a47d-ec732eebc102">
