### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by mpilomthiyane97** [NokulungaM/DataForgeAI-Capstone-FullStack#84]
## Task Description 
-Landing page with staged recipes and link to a youtube video cooking tutorial

## Task Breakdown

- [ ] Landing page UI
- [ ] Staged recipes
- [ ] Youtube links
- [ ] Search for recipes button(navbar)
- [ ] Meal-plan button(navbar)
- [ ] Community button(navbar)
- [ ] Home button(navbar
